services:
  moodle:
    image: moodlehq/moodle-php-apache:8.0
    container_name: moodle
    ports:
      - "8000:80"
    volumes:
      - ./moodle:/var/www/html
      - moodledata:/var/www/moodledata
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBHOST: database
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: moodle
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBPORT: 5432

  database:
    image: postgres:13
    container_name: moodle-database
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodle
      POSTGRES_DB: moodle
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
  moodledata:
